version: '3'
services:
    #nimbus主机始终需要排在最前面
    jstormcluster-offline-1:
        image: zhitom/docker-jstorm-cluster:latest
        hostname: jstormcluster-offline-1
        ports:
          - "30000:30000"
        environment:
          JSTORM_CLUSTER: /jstorm-cluster/offline
          JSTORM_CONF_DIR: /jstorm-cluster/offline/jstormcluster-offline-1/data
          #下面STORMYAML打头的环境变量会覆盖到集群配置文件里边，注意value的格式需符合yaml语法，并用引号引起来
          #所以产生的storm.yaml都是单行配置
          STORMYAML_STORM_ZOOKEEPER_SERVERS: '[poffline_zkcluster-offline-1_1,poffline_zkcluster-offline-2_1,poffline_zkcluster-offline-3_1]'
          STORMYAML_STORM_LOCAL_DIR: /jstorm-cluster/offline/jstormcluster-offline-1/data
          STORMYAML_SUPERVISOR_SLOTS_PORTS: '[30000,30001,30002]'
          STORMYAML_NIMBUS_SEEDS: '[jstormcluster-offline-1]'
        volumes:
            - /jstorm-cluster-volume/offline/bin:/jstorm-cluster/offline/bin
            - /jstorm-cluster-volume/offline/jstormcluster-offline-1/data:/jstorm-cluster/offline/jstormcluster-offline-1/data
            - /jstorm-cluster-volume/offline/jstormcluster-offline-1/log:/jstorm-cluster/offline/jstormcluster-offline-1/log
        #entrypoint: [/jstorm-cluster/offline/bin/jstorm.sh,offline,start,nimbus]
        entrypoint: [/jstorm-cluster/offline/bin/jstorm.sh,offline,bash]
        restart: always
        external_links:
            - poffline_zkcluster-offline-1_1:zookeeper1
            - poffline_zkcluster-offline-2_1:zookeeper2
            - poffline_zkcluster-offline-3_1:zookeeper3
        
    jstormcluster-offline-2:
        image: zhitom/docker-jstorm-cluster:latest
        hostname: jstormcluster-offline-2
        ports:
          - "30001:30001"
        environment:
          JSTORM_CLUSTER: /jstorm-cluster/offline
          JSTORM_CONF_DIR: /jstorm-cluster/offline/jstormcluster-offline-1/data
          #下面STORMYAML打头的环境变量会覆盖到集群配置文件里边，注意value的格式需符合yaml语法，并用引号引起来
          #所以产生的storm.yaml都是单行配置
          STORMYAML_STORM_ZOOKEEPER_SERVERS: '[poffline_zkcluster-offline-1_1,poffline_zkcluster-offline-2_1,poffline_zkcluster-offline-3_1]'
          STORMYAML_STORM_LOCAL_DIR: /jstorm-cluster/offline/jstormcluster-offline-2/data
          STORMYAML_SUPERVISOR_SLOTS_PORTS: '[30000,30001,30002]'
          STORMYAML_NIMBUS_SEEDS: '[jstormcluster-offline-2]'
        volumes:
            - /jstorm-cluster-volume/offline/bin:/jstorm-cluster/offline/bin
            - /jstorm-cluster-volume/offline/jstormcluster-offline-2/data:/jstorm-cluster/offline/jstormcluster-offline-2/data
            - /jstorm-cluster-volume/offline/jstormcluster-offline-2/log:/jstorm-cluster/offline/jstormcluster-offline-2/log
        #entrypoint: [/jstorm-cluster/offline/bin/jstorm.sh,offline,start,supervisor]
        entrypoint: [/jstorm-cluster/offline/bin/jstorm.sh,offline,bash]
        restart: always
        depends_on:
            - jstormcluster-offline-1
        links:
            - jstormcluster-offline-1
        external_links:
            - poffline_zkcluster-offline-1_1:zookeeper1
            - poffline_zkcluster-offline-2_1:zookeeper2
            - poffline_zkcluster-offline-3_1:zookeeper3
    

