version: '3'
services:
    zkcluster-infomgr-1:
        image: zookeeper
        restart: always
        ports:
            - 12051:12051
            - 12081:12081
            - 12021:12021
        volumes:
            - /zookeeper-cluster-volume/infomgr/bin:/zookeeper-cluster/infomgr/bin
            - /zookeeper-cluster-volume/infomgr/zkcluster-infomgr-1/data:/zookeeper-cluster/infomgr/zkcluster-infomgr-1/data
            - /zookeeper-cluster-volume/infomgr/zkcluster-infomgr-1/datalog:/zookeeper-cluster/infomgr/zkcluster-infomgr-1/datalog
            - /zookeeper-cluster-volume/infomgr/zkcluster-infomgr-1/log:/zookeeper-cluster/infomgr/zkcluster-infomgr-1/log
        hostname: zkcluster-infomgr-1
        environment:
            JVMFLAGS: "-Xmx64M -Xms64M"
            ZOO_MY_ID: 1
            ZOO_PORT: 12021
            ZOO_DATA_DIR: /zookeeper-cluster/infomgr/zkcluster-infomgr-1/data
            ZOO_DATA_LOG_DIR: /zookeeper-cluster/infomgr/zkcluster-infomgr-1/datalog
            ZOO_LOG_DIR: /zookeeper-cluster/infomgr/zkcluster-infomgr-1/log
            ZOO_SERVERS: server.1=zkcluster-infomgr-1:12051:12081 server.2=zkcluster-infomgr-2:12052:12082 server.3=zkcluster-infomgr-3:12053:12083
        entrypoint: /zookeeper-cluster/infomgr/bin/docker-entrypoint.sh
        command: ["zkServer.sh", "start"]

    zkcluster-infomgr-2:
        image: zookeeper
        restart: always
        ports:
            - 12052:12052
            - 12082:12082
            - 12022:12022
        hostname: zkcluster-infomgr-2
        volumes:
            - /zookeeper-cluster-volume/infomgr/bin:/zookeeper-cluster/infomgr/bin
            - /zookeeper-cluster-volume/infomgr/zkcluster-infomgr-2/data:/zookeeper-cluster/infomgr/zkcluster-infomgr-2/data
            - /zookeeper-cluster-volume/infomgr/zkcluster-infomgr-2/datalog:/zookeeper-cluster/infomgr/zkcluster-infomgr-2/datalog
            - /zookeeper-cluster-volume/infomgr/zkcluster-infomgr-2/log:/zookeeper-cluster/infomgr/zkcluster-infomgr-2/log
        environment:
            JVMFLAGS: "-Xmx64M -Xms64M"
            ZOO_MY_ID: 2
            ZOO_PORT: 12022
            ZOO_DATA_DIR: /zookeeper-cluster/infomgr/zkcluster-infomgr-2/data
            ZOO_DATA_LOG_DIR: /zookeeper-cluster/infomgr/zkcluster-infomgr-2/datalog
            ZOO_LOG_DIR: /zookeeper-cluster/infomgr/zkcluster-infomgr-2/log
            ZOO_SERVERS: server.1=zkcluster-infomgr-1:12051:12081 server.2=zkcluster-infomgr-2:12052:12082 server.3=zkcluster-infomgr-3:12053:12083
        entrypoint: /zookeeper-cluster/infomgr/bin/docker-entrypoint.sh
        command: ["zkServer.sh", "start"]

    zkcluster-infomgr-3:
        image: zookeeper
        restart: always
        ports:
            - 12053:12053
            - 12083:12083
            - 12023:12023
        volumes:
            - /zookeeper-cluster-volume/infomgr/bin:/zookeeper-cluster/infomgr/bin
            - /zookeeper-cluster-volume/infomgr/zkcluster-infomgr-3/data:/zookeeper-cluster/infomgr/zkcluster-infomgr-3/data
            - /zookeeper-cluster-volume/infomgr/zkcluster-infomgr-3/datalog:/zookeeper-cluster/infomgr/zkcluster-infomgr-3/datalog
            - /zookeeper-cluster-volume/infomgr/zkcluster-infomgr-3/log:/zookeeper-cluster/infomgr/zkcluster-infomgr-3/log
        hostname: zkcluster-infomgr-3
        environment:
            JVMFLAGS: "-Xmx64M -Xms64M"
            ZOO_MY_ID: 3
            ZOO_PORT: 12023
            ZOO_DATA_DIR: /zookeeper-cluster/infomgr/zkcluster-infomgr-3/data
            ZOO_DATA_LOG_DIR: /zookeeper-cluster/infomgr/zkcluster-infomgr-3/datalog
            ZOO_LOG_DIR: /zookeeper-cluster/infomgr/zkcluster-infomgr-3/log
            ZOO_SERVERS: server.1=zkcluster-infomgr-1:12051:12081 server.2=zkcluster-infomgr-2:12052:12082 server.3=zkcluster-infomgr-3:12053:12083
        entrypoint: /zookeeper-cluster/infomgr/bin/docker-entrypoint.sh
        command: ["zkServer.sh", "start"]


