version: '3'
services:
    zkcluster-autorule-1:
        image: zookeeper
        restart: always
        ports:
            - 12045:12045
            - 12075:12075
            - 12015:12015
        volumes:
            - /zookeeper-cluster-volume/autorule/bin:/zookeeper-cluster/autorule/bin
            - /zookeeper-cluster-volume/autorule/zkcluster-autorule-1/data:/zookeeper-cluster/autorule/zkcluster-autorule-1/data
            - /zookeeper-cluster-volume/autorule/zkcluster-autorule-1/datalog:/zookeeper-cluster/autorule/zkcluster-autorule-1/datalog
            - /zookeeper-cluster-volume/autorule/zkcluster-autorule-1/log:/zookeeper-cluster/autorule/zkcluster-autorule-1/log
        hostname: zkcluster-autorule-1
        environment:
            JVMFLAGS: "-Xmx64M -Xms64M"
            ZOO_MY_ID: 1
            ZOO_PORT: 12015
            ZOO_DATA_DIR: /zookeeper-cluster/autorule/zkcluster-autorule-1/data
            ZOO_DATA_LOG_DIR: /zookeeper-cluster/autorule/zkcluster-autorule-1/datalog
            ZOO_LOG_DIR: /zookeeper-cluster/autorule/zkcluster-autorule-1/log
            ZOO_SERVERS: server.1=zkcluster-autorule-1:12045:12075 server.2=zkcluster-autorule-2:12046:12076 server.3=zkcluster-autorule-3:12047:12077
        entrypoint: /zookeeper-cluster/autorule/bin/docker-entrypoint.sh
        command: ["zkServer.sh", "start"]

    zkcluster-autorule-2:
        image: zookeeper
        restart: always
        ports:
            - 12046:12046
            - 12076:12076
            - 12016:12016
        hostname: zkcluster-autorule-2
        volumes:
            - /zookeeper-cluster-volume/autorule/bin:/zookeeper-cluster/autorule/bin
            - /zookeeper-cluster-volume/autorule/zkcluster-autorule-2/data:/zookeeper-cluster/autorule/zkcluster-autorule-2/data
            - /zookeeper-cluster-volume/autorule/zkcluster-autorule-2/datalog:/zookeeper-cluster/autorule/zkcluster-autorule-2/datalog
            - /zookeeper-cluster-volume/autorule/zkcluster-autorule-2/log:/zookeeper-cluster/autorule/zkcluster-autorule-2/log
        environment:
            JVMFLAGS: "-Xmx64M -Xms64M"
            ZOO_MY_ID: 2
            ZOO_PORT: 12016
            ZOO_DATA_DIR: /zookeeper-cluster/autorule/zkcluster-autorule-2/data
            ZOO_DATA_LOG_DIR: /zookeeper-cluster/autorule/zkcluster-autorule-2/datalog
            ZOO_LOG_DIR: /zookeeper-cluster/autorule/zkcluster-autorule-2/log
            ZOO_SERVERS: server.1=zkcluster-autorule-1:12045:12075 server.2=zkcluster-autorule-2:12046:12076 server.3=zkcluster-autorule-3:12047:12077
        entrypoint: /zookeeper-cluster/autorule/bin/docker-entrypoint.sh
        command: ["zkServer.sh", "start"]

    zkcluster-autorule-3:
        image: zookeeper
        restart: always
        ports:
            - 12047:12047
            - 12077:12077
            - 12017:12017
        volumes:
            - /zookeeper-cluster-volume/autorule/bin:/zookeeper-cluster/autorule/bin
            - /zookeeper-cluster-volume/autorule/zkcluster-autorule-3/data:/zookeeper-cluster/autorule/zkcluster-autorule-3/data
            - /zookeeper-cluster-volume/autorule/zkcluster-autorule-3/datalog:/zookeeper-cluster/autorule/zkcluster-autorule-3/datalog
            - /zookeeper-cluster-volume/autorule/zkcluster-autorule-3/log:/zookeeper-cluster/autorule/zkcluster-autorule-3/log
        hostname: zkcluster-autorule-3
        environment:
            JVMFLAGS: "-Xmx64M -Xms64M"
            ZOO_MY_ID: 3
            ZOO_PORT: 12017
            ZOO_DATA_DIR: /zookeeper-cluster/autorule/zkcluster-autorule-3/data
            ZOO_DATA_LOG_DIR: /zookeeper-cluster/autorule/zkcluster-autorule-3/datalog
            ZOO_LOG_DIR: /zookeeper-cluster/autorule/zkcluster-autorule-3/log
            ZOO_SERVERS: server.1=zkcluster-autorule-1:12045:12075 server.2=zkcluster-autorule-2:12046:12076 server.3=zkcluster-autorule-3:12047:12077
        entrypoint: /zookeeper-cluster/autorule/bin/docker-entrypoint.sh
        command: ["zkServer.sh", "start"]


