version: '3'
services:
    zkcluster-f2m-1:
        image: zookeeper
        restart: always
        ports:
            - 12030:12030
            - 12060:12060
            - 12000:12000
        volumes:
            - /zookeeper-cluster-volume/f2m/bin:/zookeeper-cluster/f2m/bin
            - /zookeeper-cluster-volume/f2m/zkcluster-f2m-1/data:/zookeeper-cluster/f2m/zkcluster-f2m-1/data
            - /zookeeper-cluster-volume/f2m/zkcluster-f2m-1/datalog:/zookeeper-cluster/f2m/zkcluster-f2m-1/datalog
            - /zookeeper-cluster-volume/f2m/zkcluster-f2m-1/log:/zookeeper-cluster/f2m/zkcluster-f2m-1/log
        hostname: zkcluster-f2m-1
        environment:
            JVMFLAGS: "-Xmx64M -Xms64M"
            ZOO_MY_ID: 1
            ZOO_PORT: 12000
            ZOO_DATA_DIR: /zookeeper-cluster/f2m/zkcluster-f2m-1/data
            ZOO_DATA_LOG_DIR: /zookeeper-cluster/f2m/zkcluster-f2m-1/datalog
            ZOO_LOG_DIR: /zookeeper-cluster/f2m/zkcluster-f2m-1/log
            ZOO_SERVERS: server.1=zkcluster-f2m-1:12030:12060 server.2=zkcluster-f2m-2:12031:12061 server.3=zkcluster-f2m-3:12032:12062
        entrypoint: /zookeeper-cluster/f2m/bin/docker-entrypoint.sh
        command: ["zkServer.sh", "start"]

    zkcluster-f2m-2:
        image: zookeeper
        restart: always
        ports:
            - 12031:12031
            - 12061:12061
            - 12001:12001
        hostname: zkcluster-f2m-2
        volumes:
            - /zookeeper-cluster-volume/f2m/bin:/zookeeper-cluster/f2m/bin
            - /zookeeper-cluster-volume/f2m/zkcluster-f2m-2/data:/zookeeper-cluster/f2m/zkcluster-f2m-2/data
            - /zookeeper-cluster-volume/f2m/zkcluster-f2m-2/datalog:/zookeeper-cluster/f2m/zkcluster-f2m-2/datalog
            - /zookeeper-cluster-volume/f2m/zkcluster-f2m-2/log:/zookeeper-cluster/f2m/zkcluster-f2m-2/log
        environment:
            JVMFLAGS: "-Xmx64M -Xms64M"
            ZOO_MY_ID: 2
            ZOO_PORT: 12001
            ZOO_DATA_DIR: /zookeeper-cluster/f2m/zkcluster-f2m-2/data
            ZOO_DATA_LOG_DIR: /zookeeper-cluster/f2m/zkcluster-f2m-2/datalog
            ZOO_LOG_DIR: /zookeeper-cluster/f2m/zkcluster-f2m-2/log
            ZOO_SERVERS: server.1=zkcluster-f2m-1:12030:12060 server.2=zkcluster-f2m-2:12031:12061 server.3=zkcluster-f2m-3:12032:12062
        entrypoint: /zookeeper-cluster/f2m/bin/docker-entrypoint.sh
        command: ["zkServer.sh", "start"]

    zkcluster-f2m-3:
        image: zookeeper
        restart: always
        ports:
            - 12032:12032
            - 12062:12062
            - 12002:12002
        volumes:
            - /zookeeper-cluster-volume/f2m/bin:/zookeeper-cluster/f2m/bin
            - /zookeeper-cluster-volume/f2m/zkcluster-f2m-3/data:/zookeeper-cluster/f2m/zkcluster-f2m-3/data
            - /zookeeper-cluster-volume/f2m/zkcluster-f2m-3/datalog:/zookeeper-cluster/f2m/zkcluster-f2m-3/datalog
            - /zookeeper-cluster-volume/f2m/zkcluster-f2m-3/log:/zookeeper-cluster/f2m/zkcluster-f2m-3/log
        hostname: zkcluster-f2m-3
        environment:
            JVMFLAGS: "-Xmx64M -Xms64M"
            ZOO_MY_ID: 3
            ZOO_PORT: 12002
            ZOO_DATA_DIR: /zookeeper-cluster/f2m/zkcluster-f2m-3/data
            ZOO_DATA_LOG_DIR: /zookeeper-cluster/f2m/zkcluster-f2m-3/datalog
            ZOO_LOG_DIR: /zookeeper-cluster/f2m/zkcluster-f2m-3/log
            ZOO_SERVERS: server.1=zkcluster-f2m-1:12030:12060 server.2=zkcluster-f2m-2:12031:12061 server.3=zkcluster-f2m-3:12032:12062
        entrypoint: /zookeeper-cluster/f2m/bin/docker-entrypoint.sh
        command: ["zkServer.sh", "start"]

