version: '3'
services:
    kafkacluster-f2m-1:
        image: wurstmeister/kafka
        ports:
          - "9092:9092"
        volumes:
            - /kafka-cluster-volume/f2m/bin:/kafka-cluster/f2m/bin
            - /kafka-cluster-volume/f2m/kafkacluster-f2m-1/datalog:/kafka-cluster/f2m/kafkacluster-f2m-1/datalog
            - /kafka-cluster-volume/f2m/kafkacluster-f2m-1/log:/kafka-cluster/f2m/kafkacluster-f2m-1/log
        #  - /var/run/docker.sock:/var/run/docker.sock
        hostname: kafkacluster-f2m-1
        environment:
          #jvm
          KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
          #brokerid
          KAFKA_BROKER_ID: 1
          #进程输出的日志路径
          LOG_DIR: /kafka-cluster/f2m/kafkacluster-f2m-1/log
          #侦听客户端的本地端口
          KAFKA_PORT: 9092
          #ADVERTISED_HOST_NAME会注册到ZK，提供给外部客户端连接broker使用
          #用于拼凑KAFKA_ADVERTISED_LISTENERS变量：KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.18.0.5:9092
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper1:12000,zookeeper2:12001,zookeeper3:12002
          #kafka数据日志路径
          KAFKA_LOG_DIRS: /kafka-cluster/f2m/kafkacluster-f2m-1/datalog
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          #预定义的主题：topic:partitions:replicas:cleanup.policy
          #cleanup.policy=delete(直接删除),compact(同一个key压缩合并，仅保留最新版本数据)
          KAFKA_CREATE_TOPICS: "TopicTest:3:3"
        command: ["/kafka-cluster/f2m/bin/mykafka.sh","f2m","start"]
        #external_links 默认必须是同一个网段
        external_links:
            - pf2m_zkcluster-f2m-1_1:zookeeper1
            - pf2m_zkcluster-f2m-2_1:zookeeper2
            - pf2m_zkcluster-f2m-3_1:zookeeper3
    kafkacluster-f2m-2:
        image: wurstmeister/kafka
        ports:
          - "9093:9093"
        volumes:
            - /kafka-cluster-volume/f2m/bin:/kafka-cluster/f2m/bin
            - /kafka-cluster-volume/f2m/kafkacluster-f2m-2/datalog:/kafka-cluster/f2m/kafkacluster-f2m-2/datalog
            - /kafka-cluster-volume/f2m/kafkacluster-f2m-2/log:/kafka-cluster/f2m/kafkacluster-f2m-2/log
        #  - /var/run/docker.sock:/var/run/docker.sock
        hostname: kafkacluster-f2m-2
        environment:
          #jvm
          KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
          #brokerid
          KAFKA_BROKER_ID: 2
          #进程输出的日志路径
          LOG_DIR: /kafka-cluster/f2m/kafkacluster-f2m-2/log
          #侦听客户端的本地端口
          KAFKA_PORT: 9093
          #ADVERTISED会注册到ZK，提供给外部客户端连接broker使用
          #用于拼凑KAFKA_ADVERTISED_LISTENERS变量：KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.18.0.5:9092
          KAFKA_ADVERTISED_PORT: 9093
          KAFKA_ZOOKEEPER_CONNECT: zookeeper1:12000,zookeeper2:12001,zookeeper3:12002
          #kafka数据日志路径
          KAFKA_LOG_DIRS: /kafka-cluster/f2m/kafkacluster-f2m-2/datalog
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
          #预定义的主题：topic:partitions:replicas:cleanup.policy
          #cleanup.policy=delete(直接删除),compact(同一个key压缩合并，仅保留最新版本数据)
          KAFKA_CREATE_TOPICS: "TopicTest:3:3"
        command: ["/kafka-cluster/f2m/bin/mykafka.sh","f2m","start"]
        #external_links 默认必须是同一个网段
        external_links:
            - pf2m_zkcluster-f2m-1_1:zookeeper1
            - pf2m_zkcluster-f2m-2_1:zookeeper2
            - pf2m_zkcluster-f2m-3_1:zookeeper3
    kafkacluster-f2m-3:
        image: wurstmeister/kafka
        ports:
          - "9094:9094"
        volumes:
            - /kafka-cluster-volume/f2m/bin:/kafka-cluster/f2m/bin
            - /kafka-cluster-volume/f2m/kafkacluster-f2m-3/datalog:/kafka-cluster/f2m/kafkacluster-f2m-3/datalog
            - /kafka-cluster-volume/f2m/kafkacluster-f2m-3/log:/kafka-cluster/f2m/kafkacluster-f2m-3/log
        #  - /var/run/docker.sock:/var/run/docker.sock
        hostname: kafkacluster-f2m-3
        environment:
          #jvm
          KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
          #brokerid
          KAFKA_BROKER_ID: 3
          #进程输出的日志路径
          LOG_DIR: /kafka-cluster/f2m/kafkacluster-f2m-3/log
          #侦听客户端的本地端口
          KAFKA_PORT: 9094
          #ADVERTISED会注册到ZK，提供给外部客户端连接broker使用
          #用于拼凑KAFKA_ADVERTISED_LISTENERS变量：KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.18.0.5:9092
          KAFKA_ADVERTISED_PORT: 9094
          KAFKA_ZOOKEEPER_CONNECT: zookeeper1:12000,zookeeper2:12001,zookeeper3:12002
          #kafka数据日志路径
          KAFKA_LOG_DIRS: /kafka-cluster/f2m/kafkacluster-f2m-3/datalog
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
          #预定义的主题：topic:partitions:replicas:cleanup.policy
          #cleanup.policy=delete(直接删除),compact(同一个key压缩合并，仅保留最新版本数据)
          KAFKA_CREATE_TOPICS: "TopicTest:3:3"
        command: ["/kafka-cluster/f2m/bin/mykafka.sh","f2m","start"]
        #external_links 默认必须是同一个网段
        external_links:
            - pf2m_zkcluster-f2m-1_1:zookeeper1
            - pf2m_zkcluster-f2m-2_1:zookeeper2
            - pf2m_zkcluster-f2m-3_1:zookeeper3
